# Generated by Django 3.2.13 on 2022-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
